### ISSUE TITLE
Decide where to store daily run data and setup db communication

### ISSUE THREAD

**Issue by leopoldroos** [hejare/jaws#17]
Including its config (and graphs?)

**Comment by leopoldroos** [comment]
GCP - Firestore?

**Comment by GLiljegren** [comment]
Specify which data should be saved and how to structure it

**Comment by annagustavsson** [comment]
### Mongo DB
**Pros**
- Open source, there exists a serverless plan
- Support complex queries 
- Can add middleware to 


**Cons**
- Have to index the documents manually

### Firebase Cloud Firestore
**Pros**
- Has support for subcollections that can be queried directly. 
- Automatically indexes the documents

**Cons**
- Does not support as complex queries as Mongo DB
